spring:
  aop:
    proxy-target-class: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: 135223  
    druid:
      max-active: 20
      max-wait: 5000
      initial-size: 1
      validation-query: SELECT 'X'   #验证连接
      enable: true



#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

  global-config:
    db-config:
      id-type: auto
  configuration:
    # log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


knife4j:
  ## 是否为生产环境(false为可以访问接口文档地址，true为不可访问接口文档地址)
  production: false
  # 是否使用knife4j的增强功能
  enable: true
  setting:
    swagger-model-name: 实体类列表
    # 是否自定义底部栏
    enable-footer-custom: true
    # 自定义底部栏内容
    footer-custom-content: spb3_demo
    # 针对RequestMapping的接口请求类型,在不指定参数类型的情况下,如果不过滤,默认会显示7个类型的接口地址参数,如果开启此配置,默认展示一个Post类型的接口地址
    enable-filter-multipart-apis: true
    # 具体接口的过滤类型
    enable-filter-multipart-api-method-type: GET

shiro:
  hash-algorithm-name: SHA-256
  hash-iterations: 2
  anon-urls:
    - /doc.html**
    - /webjars/**/**
    - /swagger-resources/**
    - /v2/**
    - /v3/**
    - /resources/**
    - /login/login
    - /login/getCode
    - /user/register
    - /commission/list
    - /commission/getById**
  login-url: /login/login
  log-out-url: /login/logout
  authc-urls:
    - /**
server:
  port: 8888